name: uttt_website
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: moserd <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.0
  json_serializable: ^2.0.0

dependencies:
  uttt_package:
    path: ../uttt_package
  json_annotation: ^2.0.0
  chartjs:
    git: https://github.com/google/chartjs.dart.git